### ISSUE TITLE
tabs in run.py (PEP8 compliance)

### ISSUE THREAD

**Issue by jonahweissman** [Tim-Jackins/slackbot#2]
## Description

According to [the PEP8 spec](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces), you're not supposed to mix tabs and spaces. I think they're mostly talking about mixing within the same file. Still, you use tabs in `run.py` and spaces in the other files. Maybe it would be better to use spaces across the board.

> ### Tabs or Spaces?
> Spaces are the preferred indentation method.
> 
> Tabs should be used solely to remain consistent with code that is already indented with tabs.

### What type of issue is this? (place an x in one of the [ ])
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an x in each of the [ ])
- [ ] I've read and understood the Contributing guidelines and have done my best effort to follow them. **<-- I could not find this**
- [x] I've read and agree to the Code of Conduct.
- [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by Tim-Jackins** [comment]
Fixes in commit 51ac0d2d684d954e874115196ed6027053985601
